version : '3'
services:
        db:
           image : mysql
           volumes:
                   - ../mysql:/var/lib/mysql
           ports:
                   - "3306:3306"
           environment:
                   - MYSQL_ROOT_PASSWORD=root
        api:
            image: api
            volumes :
                    - ./:/web_api
            ports:
                    - "7999:7999"
            restart: always



        

