version : '3'
networks:
        db_net:
                driver: bridge
                ipam:
                        config:
                                - subnet: 192.168.2.0/24
services:
        api:
            image: dev_web_apiv_0
            networks:
                db_net:
                        ipv4_address: 192.168.2.11
            volumes :
                    - ./:/web_api
            command: uvicorn main:app --host 192.168.2.11 --port 8000
            ports:
                    - "8000:8000"

        

